export const PAGE_ROUTES = {
  CART: '/cart',

  CUSTOMER_ACQUISITION_AGENT_DASHBOARD: '/caa/dashboard',
  CUSTOMER_ACQUISITION_AGENT_CUSTOMERS: '/caa/customer',
  CUSTOMER_ACQUISITION_ONBOARDED_CUSTOMERS: '/caa/onboarded-customers',

  MARKET_PLACE: '/market-place',
  PHONE_VERIFICATION: '/verify',
  ORDER_DETAILS: '/order-details',
  NO_VERIFICATION: '/no-verification',
  UPDATE_BUSINESS_PROFILE: '/update-business',

  NOT_ORDERING: '/sr/not-ordering',
  SALES_REP_CUSTOMER: '/sr/customer',
  SALES_REP_DASHBOARD: '/sr/dashboard',
  SALES_REP_VISIT_PLAN: '/sr/visit-plan',
  SALES_REP_CAPTURE_SHOP: '/sr/capture-shop',
  SALES_REP_ASSIGNED_CUSTOMERS: '/sr/assigned-customers',

  TELE_SALES_DASHBOARD: '/ts/dashboard',
  TELE_SALES_CUSTOMER: '/ts/customer',
  TELE_SALES_CALL_PLAN: '/ts/call-plan',
  TELE_SALES_NOT_ORDERING: '/ts/not-ordering',
  TELE_SALES_ASSIGNED_CUSTOMERS: '/ts/assigned-customers',
  ONBOARDING_CREATE_DRIVER: '/onboard-driver',
  ONBOARD_SUCCESS: '/lm/onboard-success',
  VERIFY_PHONE_NUMBER: '/verify-phone',
  VEHICLE_AUTHENTICATION: '/vehicle-authentication',
  BACK_OFFICE_DASHBOARD: '/bo/dashboard',
  BACK_OFFICE_RETAILERS: '/bo/retailers',
  BACK_OFFICE_WHOLESALERS: '/bo/stock-update',
  BACK_OFFICE_RETAILER_PROFILE: '/bo/retailer-profile',
  WHOLESALER_ACCOUNT_OFFICER_DASHBOARD: '/wao/dashboard',
  BACK_OFFICE_WHOLESALER_PROFILE: '/bo/wholesaler-profile',
  BACK_OFFICE_TASK_COMPLAINT: '/bo/complaint',
  BACK_OFFICE_CREATE_AGENT: '/bo/create-agent',
  BACK_OFFICE_CREATE_DRIVER: '/bo/onboard-driver',
  BACK_OFFICE_DRIVER_VEHICLE_AUTHENTICATION: '/bo/vehicle-authentication',
  BACK_OFFICE_DRIVER_VERIFY_PHONE: '/bo/verify-phone',
  BACK_OFFICE_ALL_AGENTS: '/bo/agent',
  BACK_OFFICE_MODIFY_DRIVER: '/bo/modify-driver',
  BACK_OFFICE_LIST_SKU: '/bo/product-sku/list',
  BACK_OFFICE_EDIT_SKU: '/bo/product-sku/edit',
  BACK_OFFICE_CREATE_SKU: '/bo/product-sku/create',
  BACK_OFFICE_PICK_UP_LIST: '/bo/pick-up/list',
  BACK_OFFICE_PURCHASE_REQUISITION: '/bo/purchase-requisition/list',

  LM_DASHBOARD: '/lm/dashboard',
  LM_DRIVER_ORDER: '/lm/driver-order',
  LM_DRIVER_PICKUP: '/lm/driver-pickup',
  LM_DRIVER_PROFILE: '/lm/driver-profile',
  LM_DRIVER_CLIENT: '/lm/driver-client',
  LM_ONBOARD_DRIVER: '/lm/onboard-driver',
  LM_DRIVER_DELIVERY: '/lm/driver-delivery',
};
